### ISSUE TITLE
User - Create Topic - Discuss things and event of interest

### ISSUE THREAD

**Issue by Skiingseason** [sopra-fs24-group-05/sopra-fs24-group-05-server#21]
>As a user I want to create a topic so I can discuss things and event of my interest with others

**Estimate:** 16 Hours

**Acceptance Criteria:**

- [ ] On lobby page, user are provide with a button to create a topic
- [x] Once click the create topic button user will be naviaged to Create page to enter detail information
- [x] After clicking the confirm button on create page, a request will be sent to backend
- [x] Backend should properly handle the request, and return the content to the frontend to render the topic page
- [ ] Once the topic is successfully create, User will be direct to the specifc topic page

**Tasks**
- [x] create a internal representation Class of Topic `/Entity/Topic.java`
- [x] implement `TopicController.java` and corresponding helper methods in `TopicService.java`
- [x] sopra-fs24-group-05/sopra-fs24-group-05-client#5

**Comment by yimxia** [comment]
commit 889757755f1894e2ee581d80aaccf68ec3cad0ab
